"""Pairing API routes - QR code pairing for mobile app."""

import base64
import re
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse, Response

from models import (
    PairCodeVerifyRequest,
    PairVerifyRequest,
    PushTokenRegisterRequest,
    SSOPairRequest,
)
from pairing.pairing import (
    RateLimiter,
    build_current_pairing_qr_result,
    get_pair_token_status_for_current_server,
    get_pairing_status_for_current_server,
    register_push_token_for_current_server,
    revoke_paired_client_for_current_server,
    verify_pairing_code_for_current_server,
    verify_sso_pairing_for_current_server,
)
from pairing.pairing_page import make_qr_png_base64
from pairing.pairing_page_service import build_pairing_page_html_for_current_server
from remote.remote_access_service import verify_pair_token_for_current_server

from .deps import require_local_access, require_localhost_only, verify_api_key
from .result_response import as_route_response

# Rate limiting constants for pairing endpoints
TOKEN_STATUS_MAX_ATTEMPTS = 20
TOKEN_STATUS_LOCKOUT_SECONDS = 300
VERIFY_MAX_ATTEMPTS = 10
VERIFY_LOCKOUT_SECONDS = 600
RATE_LIMIT_WINDOW_SECONDS = 60

# Pair tokens are generated by ``secrets.token_hex(16)`` — 32 lower-case
# hex characters. Reject anything that does not match before invoking the
# pairing service so token enumeration is cheap to detect and burns the
# attacker's IP rate-limit budget regardless.
_PAIR_TOKEN_RE = re.compile(r"^[0-9a-f]{32}$")

router = APIRouter(tags=["pairing"])

# Rate limiters for unauthenticated endpoints
_token_status_limiter = RateLimiter(
    max_attempts=TOKEN_STATUS_MAX_ATTEMPTS,
    window_seconds=RATE_LIMIT_WINDOW_SECONDS,
    lockout_seconds=TOKEN_STATUS_LOCKOUT_SECONDS,
)
_verify_limiter = RateLimiter(
    max_attempts=VERIFY_MAX_ATTEMPTS,
    window_seconds=RATE_LIMIT_WINDOW_SECONDS,
    lockout_seconds=VERIFY_LOCKOUT_SECONDS,
)


@router.get("/api/pair/qr", dependencies=[Depends(require_localhost_only)])
async def get_pair_qr() -> JSONResponse:
    """Get QR code pairing data.

    Only accessible from the server machine for security.
    """
    from fastapi.responses import JSONResponse
    result = build_current_pairing_qr_result()
    response_data = result.as_response_fields() if hasattr(result, 'as_response_fields') else result.__dict__
    return JSONResponse(
        content=response_data,
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
            "Expires": "0",
        },
    )


@router.get("/api/pair/qr-image", dependencies=[Depends(require_localhost_only)])
async def get_pair_qr_image() -> Response:
    """Get QR code as PNG image for dashboard display.

    Only accessible from the server machine for security.
    """
    result = build_current_pairing_qr_result()
    if not result.success or not result.qr_url:
        return Response(content=b"", media_type="image/png", status_code=500)

    qr_base64 = make_qr_png_base64(result.qr_url)
    qr_bytes = base64.b64decode(qr_base64)
    return Response(
        content=qr_bytes,
        media_type="image/png",
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
            "Expires": "0",
        },
    )


@router.get(
    "/pair",
    response_class=HTMLResponse,
    dependencies=[Depends(require_localhost_only)],
)
async def get_pair_page(embed: bool = False) -> HTMLResponse:
    """Show QR code pairing page in browser.

    This page is ONLY accessible from localhost (127.0.0.1).
    Must be opened on the same machine where the server is running.

    Args:
        embed: If True, hides title and dashboard link (for iframe embed in dashboard modal)
    """
    result = build_pairing_page_html_for_current_server(embed=embed)
    return HTMLResponse(
        content=result.content,
        status_code=result.status_code,
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
            "Expires": "0",
        },
    )


@router.get("/api/pair/token-status/{token}")
async def get_token_status(token: str, request: Request) -> dict[str, Any]:
    """Check if a pairing token has been used.

    Rate limited and format-validated to prevent token enumeration.
    """
    client_ip = _get_client_ip(request)
    is_allowed, remaining = _token_status_limiter.check_rate_limit(client_ip)

    if not is_allowed:
        raise HTTPException(
            status_code=429,
            detail=f"Too many requests. Try again in {remaining} seconds."
        )

    # Malformed tokens can never be valid; burn the attacker's budget
    # without ever invoking the pairing service.
    if not _PAIR_TOKEN_RE.match(token):
        _token_status_limiter.record_attempt(client_ip, success=False)
        raise HTTPException(status_code=400, detail="Invalid pairing token format.")

    result = get_pair_token_status_for_current_server(token)

    # Record attempt (non-existent tokens count as failed attempts)
    if not result.exists:
        _token_status_limiter.record_attempt(client_ip, success=False)

    return result.as_response_fields()


def _get_client_ip(request: Request) -> str:
    """Extract client IP from request, with secure proxy handling.

    Security: Only trust specific headers from known proxies.
    - CF-Connecting-IP: Trusted from Cloudflare Tunnel
    - Direct connection: Use request.client.host
    - Untrusted headers (X-Forwarded-For, X-Real-IP): Only as fallback
    """
    # Priority 1: Cloudflare Tunnel header (trusted)
    cf_ip = request.headers.get("CF-Connecting-IP")
    if cf_ip:
        return cf_ip.strip()

    # Priority 2: Direct client connection (most reliable)
    if request.client and request.client.host:
        # If this is a local request, trust it
        client_host = request.client.host
        if client_host in ("127.0.0.1", "::1", "localhost"):
            return client_host
        # For non-local direct connections, use the actual client IP
        # Don't trust X-Forwarded-For from unknown sources
        return client_host

    # Priority 3: Fallback to forwarded headers (less secure, for compatibility)
    forwarded_for = request.headers.get("X-Forwarded-For")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()

    real_ip = request.headers.get("X-Real-IP")
    if real_ip:
        return real_ip.strip()

    return "unknown"


@router.post("/api/pair/code", dependencies=[Depends(require_local_access)], response_model=None)
async def verify_pairing_code(request: Request, body: PairCodeVerifyRequest) -> dict[str, Any] | Response:
    """Verify a 6-digit pairing code and return a pair_token.

    Only accessible from local network for security (prevents external brute-force).
    """
    client_ip = _get_client_ip(request)
    result = verify_pairing_code_for_current_server(body.code, client_ip=client_ip)
    return as_route_response(result)


@router.post("/api/pair/verify", response_model=None)
async def verify_pair_token(request: Request, body: PairVerifyRequest) -> dict[str, Any] | Response:
    """Verify a pairing token and issue an API key.

    Rate limited and format-validated to prevent brute-force / enumeration.
    """
    client_ip = _get_client_ip(request)
    is_allowed, remaining = _verify_limiter.check_rate_limit(client_ip)

    if not is_allowed:
        raise HTTPException(
            status_code=429,
            detail=f"Too many verification attempts. Try again in {remaining} seconds."
        )

    # Reject malformed tokens cheaply, but still charge the attacker's
    # verify budget so garbage payloads don't get a free pass.
    if not _PAIR_TOKEN_RE.match(body.pair_token):
        _verify_limiter.record_attempt(client_ip, success=False)
        raise HTTPException(status_code=400, detail="Invalid pairing token format.")

    result = await verify_pair_token_for_current_server(
        pair_token=body.pair_token,
        client_id=body.client_id,
        device_name=body.device_name,
        firebase_id_token=body.firebase_id_token,
        firebase_refresh_token=body.firebase_refresh_token,
        force_replace=body.force_replace,
    )

    # Record attempt
    _verify_limiter.record_attempt(client_ip, success=result.success)

    return as_route_response(result)


@router.post("/api/pair/sso", dependencies=[Depends(require_local_access)], response_model=None)
async def verify_sso_pairing(request: Request, body: SSOPairRequest) -> dict[str, Any] | Response:
    """Verify Firebase SSO and issue API key if user owns this server.

    This endpoint is called when app selects a remote server from Firebase.
    Only accessible from local network - first connection must be on same network.
    Server verifies the ID token and checks ownership before issuing API key.
    """
    client_ip = _get_client_ip(request)
    is_allowed, remaining = _verify_limiter.check_rate_limit(client_ip)

    if not is_allowed:
        raise HTTPException(
            status_code=429,
            detail=f"Too many verification attempts. Try again in {remaining} seconds."
        )

    result = await verify_sso_pairing_for_current_server(
        firebase_id_token=body.firebase_id_token,
        firebase_refresh_token=body.firebase_refresh_token,
        client_id=body.client_id,
        device_name=body.device_name,
        force_replace=body.force_replace,
    )

    # Record attempt
    _verify_limiter.record_attempt(client_ip, success=result.success)

    return as_route_response(result)


@router.get("/api/pair/status", dependencies=[Depends(verify_api_key)])
async def get_pair_status() -> dict[str, Any]:
    """Get current pairing status."""
    return get_pairing_status_for_current_server().as_response_fields()


@router.post("/api/pair/push-token", response_model=None)
async def register_push_token(
    body: PushTokenRegisterRequest,
    api_key: str = Depends(verify_api_key),
) -> dict[str, Any]:
    """Register (or refresh) this device's FCM token for push delivery.

    Called once right after pairing and again whenever the OS rotates the
    token. The token is attached to whichever paired client authenticated
    this request — a device can only ever register a token for its own
    pairing, never for a client_id it merely names in the body.

    Without this endpoint a notify step's message is stored on the server
    but the phone never learns about it until the inbox is opened by hand;
    this is what turns that pull into a push.
    """
    if not api_key or api_key == "__ip_login__":
        raise HTTPException(
            status_code=401,
            detail="A paired API key is required to register a push token.",
        )

    registered = register_push_token_for_current_server(api_key, body.token, platform=body.platform)
    if not registered:
        raise HTTPException(
            status_code=404,
            detail="No paired client found for this API key.",
        )
    return {"success": True}


@router.delete(
    "/api/pair/clients/{client_id}",
    dependencies=[Depends(require_localhost_only)],
    response_model=None,
)
async def revoke_paired_client(client_id: str) -> dict[str, Any] | Response:
    """Revoke a paired client's API key.

    This is a dashboard management endpoint - only accessible on the server PC.
    """
    result = revoke_paired_client_for_current_server(client_id)
    return as_route_response(result)


@router.post("/api/pair/show-qr", dependencies=[Depends(require_local_access)])
async def show_qr_on_server() -> dict[str, Any]:
    """Open QR code page in browser on the SERVER PC.

    Called from mobile app to trigger QR display on the PC where server is running.
    Uses webbrowser.open() which runs on the SERVER machine, not the mobile device.
    No authentication required - QR display is safe and useful for initial pairing.
    """
    import webbrowser
    from pairing.pairing_qr_service import build_pairing_qr_payload_for_current_server, open_pairing_page

    try:
        payload = build_pairing_qr_payload_for_current_server()
        # pair_url is "http://localhost:{dashboard_port}/pair"
        open_pairing_page(payload.pair_url, opener=webbrowser.open)
        return {"success": True, "message": "QR code page opened in browser on PC"}
    except OSError as exc:
        return {"success": False, "error": str(exc)}
