"""Autostart service for Code Bridge server.

Manages automatic startup on system boot across platforms:
- macOS: LaunchAgent (~/Library/LaunchAgents/)
- Linux: systemd user service (~/.config/systemd/user/)
- Windows: Start Menu Startup folder
"""

from __future__ import annotations

import logging
import os
import platform
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Service identifiers
MACOS_PLIST_NAME = "com.codebridge.server.plist"
LINUX_SERVICE_NAME = "codebridge-server.service"
WINDOWS_SHORTCUT_NAME = "Code Bridge Server.lnk"


@dataclass(frozen=True)
class AutostartStatus:
    """Autostart status for dashboard."""

    available: bool  # Can autostart be configured on this platform?
    enabled: bool  # Is autostart currently enabled?
    platform: str  # Current platform (darwin, linux, windows)
    method: str  # Method used (launchagent, systemd, startup_folder, unsupported)
    path: str | None  # Path to the autostart file

    def as_dict(self) -> dict[str, Any]:
        return {
            "available": self.available,
            "enabled": self.enabled,
            "platform": self.platform,
            "method": self.method,
            "path": self.path,
        }


def _get_server_script_path() -> Path:
    """Get the path to server_cli.py."""
    return Path(__file__).parent / "server_cli.py"


def _get_python_path() -> str:
    """Get the path to the Python interpreter.

    Checks for virtual environment first (both .venv and venv),
    then falls back to system Python.
    """
    server_dir = _get_server_dir()

    # Check for virtual environment in server directory
    for venv_name in [".venv", "venv"]:
        venv_python = server_dir / venv_name / "bin" / "python"
        if venv_python.exists():
            return str(venv_python)

    # Fallback to current executable
    return sys.executable


def _get_server_dir() -> Path:
    """Get the server directory."""
    return Path(__file__).parent


# ============================================================================
# macOS LaunchAgent
# ============================================================================


def _get_macos_launchagent_path() -> Path:
    """Get the LaunchAgent plist path.

    Uses local home directory to ensure accessibility at boot time.
    """
    local_home = _get_local_home()
    return local_home / "Library" / "LaunchAgents" / MACOS_PLIST_NAME


def _get_local_home() -> Path:
    """Get a local home directory that's always available at boot.

    If the home directory is on an external volume (/Volumes/),
    use /Users/<username> instead for boot-time accessibility.
    """
    import pwd

    home = Path.home()
    username = pwd.getpwuid(os.getuid()).pw_name

    # If home is on external volume, use /Users/<username> instead
    if str(home).startswith("/Volumes/"):
        local_home = Path("/Users") / username
        if local_home.exists():
            return local_home

    return home


def _get_macos_wrapper_path() -> Path:
    """Get the path for the macOS wrapper script."""
    local_home = _get_local_home()
    return local_home / ".local" / "bin" / "codebridge-autostart.sh"


def _generate_macos_wrapper() -> str:
    """Generate wrapper script that waits for volume mount."""
    python_path = _get_python_path()
    script_path = _get_server_script_path()
    server_dir = _get_server_dir()
    server_path_str = str(server_dir)

    # Check if path is on external volume
    wait_script = ""
    if server_path_str.startswith("/Volumes/"):
        parts = server_path_str.split("/")
        if len(parts) >= 3:
            volume_path = f"/Volumes/{parts[2]}"
            wait_script = f'''
# Wait for volume to mount (max 60 seconds)
WAIT_COUNT=0
while [ ! -d "{volume_path}" ] && [ $WAIT_COUNT -lt 60 ]; do
    sleep 1
    WAIT_COUNT=$((WAIT_COUNT + 1))
done

if [ ! -d "{volume_path}" ]; then
    echo "Volume {volume_path} not mounted after 60 seconds, exiting"
    exit 1
fi

# Additional wait for filesystem to stabilize
sleep 2
'''

    return f'''#!/bin/bash
# Code Bridge Server Autostart Wrapper
# Generated by autostart_service.py
{wait_script}
cd "{server_dir}"
exec "{python_path}" "{script_path}"
'''


def _generate_macos_plist() -> str:
    """Generate LaunchAgent plist content."""
    wrapper_path = _get_macos_wrapper_path()
    local_home = _get_local_home()
    log_path = local_home / "Library" / "Logs" / "codebridge-server.log"
    error_log_path = local_home / "Library" / "Logs" / "codebridge-server-error.log"

    return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.codebridge.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>{wrapper_path}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{log_path}</string>
    <key>StandardErrorPath</key>
    <string>{error_log_path}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>
"""


def _is_macos_autostart_enabled() -> bool:
    """Check if macOS autostart is enabled."""
    plist_path = _get_macos_launchagent_path()
    return plist_path.exists()


def _enable_macos_autostart() -> tuple[bool, str]:
    """Enable macOS autostart via LaunchAgent."""
    plist_path = _get_macos_launchagent_path()
    wrapper_path = _get_macos_wrapper_path()

    try:
        # Ensure directories exist
        plist_path.parent.mkdir(parents=True, exist_ok=True)
        wrapper_path.parent.mkdir(parents=True, exist_ok=True)

        # Ensure logs directory exists
        log_dir = Path.home() / "Library" / "Logs"
        log_dir.mkdir(parents=True, exist_ok=True)

        # Write wrapper script
        wrapper_content = _generate_macos_wrapper()
        wrapper_path.write_text(wrapper_content)
        wrapper_path.chmod(0o755)  # Make executable

        # Write plist file
        plist_content = _generate_macos_plist()
        plist_path.write_text(plist_content)

        # Unload first if already loaded (ignore errors)
        subprocess.run(
            ["launchctl", "unload", str(plist_path)],
            capture_output=True,
            text=True,
        )

        # Load the LaunchAgent using bootstrap (modern macOS)
        uid = os.getuid()
        result = subprocess.run(
            ["launchctl", "bootstrap", f"gui/{uid}", str(plist_path)],
            capture_output=True,
            text=True,
        )

        # If bootstrap fails, try legacy load
        if result.returncode != 0:
            result = subprocess.run(
                ["launchctl", "load", str(plist_path)],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0 and "already loaded" not in result.stderr.lower():
                logger.warning("launchctl warning: %s", result.stderr)

        logger.info("Enabled macOS autostart: %s", plist_path)
        return True, f"Autostart enabled. Will start on next boot."

    except Exception as e:
        logger.error("Failed to enable macOS autostart: %s", e)
        return False, f"Failed to enable autostart: {e}"


def _disable_macos_autostart() -> tuple[bool, str]:
    """Disable macOS autostart."""
    plist_path = _get_macos_launchagent_path()
    wrapper_path = _get_macos_wrapper_path()

    try:
        if plist_path.exists():
            # Try bootout first (modern macOS)
            uid = os.getuid()
            subprocess.run(
                ["launchctl", "bootout", f"gui/{uid}", str(plist_path)],
                capture_output=True,
                text=True,
            )
            # Fallback: unload (legacy)
            subprocess.run(
                ["launchctl", "unload", str(plist_path)],
                capture_output=True,
                text=True,
            )
            # Remove the plist file
            plist_path.unlink()
            logger.info("Disabled macOS autostart: %s", plist_path)

        # Remove wrapper script
        if wrapper_path.exists():
            wrapper_path.unlink()

        return True, "Autostart disabled."

    except Exception as e:
        logger.error("Failed to disable macOS autostart: %s", e)
        return False, f"Failed to disable autostart: {e}"


# ============================================================================
# Linux systemd user service
# ============================================================================


def _get_linux_service_path() -> Path:
    """Get the systemd user service file path."""
    return Path.home() / ".config" / "systemd" / "user" / LINUX_SERVICE_NAME


def _generate_linux_service() -> str:
    """Generate systemd user service content."""
    python_path = _get_python_path()
    script_path = _get_server_script_path()
    server_dir = _get_server_dir()

    return f"""\
[Unit]
Description=Code Bridge Server
After=network.target

[Service]
Type=simple
WorkingDirectory={server_dir}
ExecStart={python_path} {script_path}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


def _is_linux_autostart_enabled() -> bool:
    """Check if Linux autostart is enabled."""
    service_path = _get_linux_service_path()
    if not service_path.exists():
        return False

    # Check if service is enabled
    try:
        result = subprocess.run(
            ["systemctl", "--user", "is-enabled", LINUX_SERVICE_NAME],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except Exception:
        return False


def _enable_linux_autostart() -> tuple[bool, str]:
    """Enable Linux autostart via systemd user service."""
    service_path = _get_linux_service_path()

    try:
        # Ensure systemd user directory exists
        service_path.parent.mkdir(parents=True, exist_ok=True)

        # Write service file
        service_content = _generate_linux_service()
        service_path.write_text(service_content)

        # Reload systemd user daemon
        subprocess.run(
            ["systemctl", "--user", "daemon-reload"],
            capture_output=True,
            text=True,
        )

        # Enable the service
        result = subprocess.run(
            ["systemctl", "--user", "enable", LINUX_SERVICE_NAME],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            return False, f"Failed to enable service: {result.stderr}"

        # Enable lingering so service runs without user login
        subprocess.run(
            ["loginctl", "enable-linger", os.getlogin()],
            capture_output=True,
            text=True,
        )

        logger.info("Enabled Linux autostart: %s", service_path)
        return True, f"Autostart enabled. Service: {service_path}"

    except Exception as e:
        logger.error("Failed to enable Linux autostart: %s", e)
        return False, f"Failed to enable autostart: {e}"


def _disable_linux_autostart() -> tuple[bool, str]:
    """Disable Linux autostart."""
    service_path = _get_linux_service_path()

    try:
        # Disable the service
        subprocess.run(
            ["systemctl", "--user", "disable", LINUX_SERVICE_NAME],
            capture_output=True,
            text=True,
        )

        # Stop the service if running
        subprocess.run(
            ["systemctl", "--user", "stop", LINUX_SERVICE_NAME],
            capture_output=True,
            text=True,
        )

        # Remove service file
        if service_path.exists():
            service_path.unlink()

        # Reload daemon
        subprocess.run(
            ["systemctl", "--user", "daemon-reload"],
            capture_output=True,
            text=True,
        )

        logger.info("Disabled Linux autostart: %s", service_path)
        return True, "Autostart disabled."

    except Exception as e:
        logger.error("Failed to disable Linux autostart: %s", e)
        return False, f"Failed to disable autostart: {e}"


# ============================================================================
# Windows Startup folder
# ============================================================================


def _get_windows_startup_path() -> Path:
    """Get the Windows Startup folder shortcut path."""
    # Use shell:startup to get the actual startup folder
    startup_folder = Path(os.environ.get("APPDATA", "")) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
    return startup_folder / WINDOWS_SHORTCUT_NAME


def _get_windows_bat_path() -> Path:
    """Get the path for the Windows batch file."""
    return _get_server_dir() / "start_server.bat"


def _generate_windows_bat() -> str:
    """Generate Windows batch file content."""
    python_path = _get_python_path()
    script_path = _get_server_script_path()
    server_dir = _get_server_dir()

    return f"""\
@echo off
cd /d "{server_dir}"
"{python_path}" "{script_path}"
"""


def _is_windows_autostart_enabled() -> bool:
    """Check if Windows autostart is enabled."""
    shortcut_path = _get_windows_startup_path()
    return shortcut_path.exists()


def _enable_windows_autostart() -> tuple[bool, str]:
    """Enable Windows autostart via Startup folder."""
    shortcut_path = _get_windows_startup_path()
    bat_path = _get_windows_bat_path()

    try:
        # Ensure startup folder exists
        shortcut_path.parent.mkdir(parents=True, exist_ok=True)

        # Create batch file
        bat_content = _generate_windows_bat()
        bat_path.write_text(bat_content)

        # Create shortcut using PowerShell
        # We'll create a .bat shortcut (actually just copy the bat to startup)
        # For a proper .lnk shortcut, we need PowerShell or COM
        ps_script = f"""
$WScriptShell = New-Object -ComObject WScript.Shell
$Shortcut = $WScriptShell.CreateShortcut("{shortcut_path}")
$Shortcut.TargetPath = "{bat_path}"
$Shortcut.WorkingDirectory = "{_get_server_dir()}"
$Shortcut.Description = "Code Bridge Server"
$Shortcut.Save()
"""
        result = subprocess.run(
            ["powershell", "-Command", ps_script],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            # Fallback: just copy the bat file to startup
            import shutil
            shutil.copy(bat_path, shortcut_path.with_suffix(".bat"))
            logger.info("Created startup batch file: %s", shortcut_path.with_suffix(".bat"))
            return True, f"Autostart enabled. Startup script: {shortcut_path.with_suffix('.bat')}"

        logger.info("Enabled Windows autostart: %s", shortcut_path)
        return True, f"Autostart enabled. Shortcut: {shortcut_path}"

    except Exception as e:
        logger.error("Failed to enable Windows autostart: %s", e)
        return False, f"Failed to enable autostart: {e}"


def _disable_windows_autostart() -> tuple[bool, str]:
    """Disable Windows autostart."""
    shortcut_path = _get_windows_startup_path()
    bat_shortcut_path = shortcut_path.with_suffix(".bat")

    try:
        # Remove shortcut
        if shortcut_path.exists():
            shortcut_path.unlink()
        if bat_shortcut_path.exists():
            bat_shortcut_path.unlink()

        logger.info("Disabled Windows autostart")
        return True, "Autostart disabled."

    except Exception as e:
        logger.error("Failed to disable Windows autostart: %s", e)
        return False, f"Failed to disable autostart: {e}"


# ============================================================================
# Public API
# ============================================================================


def get_autostart_status() -> AutostartStatus:
    """Get current autostart status for the platform."""
    system = platform.system().lower()

    if system == "darwin":
        return AutostartStatus(
            available=True,
            enabled=_is_macos_autostart_enabled(),
            platform="darwin",
            method="launchagent",
            path=str(_get_macos_launchagent_path()) if _is_macos_autostart_enabled() else None,
        )
    elif system == "linux":
        return AutostartStatus(
            available=True,
            enabled=_is_linux_autostart_enabled(),
            platform="linux",
            method="systemd",
            path=str(_get_linux_service_path()) if _is_linux_autostart_enabled() else None,
        )
    elif system == "windows":
        return AutostartStatus(
            available=True,
            enabled=_is_windows_autostart_enabled(),
            platform="windows",
            method="startup_folder",
            path=str(_get_windows_startup_path()) if _is_windows_autostart_enabled() else None,
        )
    else:
        return AutostartStatus(
            available=False,
            enabled=False,
            platform=system,
            method="unsupported",
            path=None,
        )


def enable_autostart() -> tuple[bool, str]:
    """Enable autostart for the current platform.

    Returns:
        Tuple of (success, message)
    """
    system = platform.system().lower()

    if system == "darwin":
        return _enable_macos_autostart()
    elif system == "linux":
        return _enable_linux_autostart()
    elif system == "windows":
        return _enable_windows_autostart()
    else:
        return False, f"Unsupported platform: {system}"


def disable_autostart() -> tuple[bool, str]:
    """Disable autostart for the current platform.

    Returns:
        Tuple of (success, message)
    """
    system = platform.system().lower()

    if system == "darwin":
        return _disable_macos_autostart()
    elif system == "linux":
        return _disable_linux_autostart()
    elif system == "windows":
        return _disable_windows_autostart()
    else:
        return False, f"Unsupported platform: {system}"


def set_autostart(enabled: bool) -> tuple[bool, str]:
    """Enable or disable autostart.

    Args:
        enabled: True to enable, False to disable

    Returns:
        Tuple of (success, message)
    """
    if enabled:
        return enable_autostart()
    else:
        return disable_autostart()
